                            Job Posts
The dataset consists of 19,000 job postings.A job posting usually has some structure, although some fields of the posting are not necessarily filled out by the client (poster).The data consists of job posts from 2004-2015

In [19]:
%matplotlib inline
%pylab inline
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import pandas as pd
import statsmodels.api as sm
import warnings
warnings.filterwarnings('ignore')
ja = pd.read_csv('D:/dataSets/job analysis/datajobposts.csv')
print (ja)

Populating the interactive namespace from numpy and matplotlib
                                                 jobpost          date  \
0      AMERIA Investment Consulting Company\r\nJOB TI...   Jan 5, 2004
1      International Research & Exchanges Board (IREX...   Jan 7, 2004
2      Caucasus Environmental NGO Network (CENN)\r\nJ...   Jan 7, 2004
3      Manoff Group\r\nJOB TITLE:  BCC Specialist\r\n...   Jan 7, 2004
4      Yerevan Brandy Company\r\nJOB TITLE:  Software...  Jan 10, 2004
5      Boutique "Appollo"\r\nJOB TITLE:  Saleswoman\r...  Jan 10, 2004
6      OSI Assistance Foundation - Armenian Branch Of...  Jan 11, 2004
7      International Research & Exchanges Board (IREX...  Jan 13, 2004
8      Yerevan Brandy Company \r\nJOB TITLE:  Assista...  Jan 13, 2004
9      American Embassy Yerevan\r\nANNOUNCEMENT NUMBE...  Jan 13, 2004
10     International Research & Exchanges Board (IREX...  Jan 13, 2004
11     International Research & Exchanges Board (IREX...  Jan 13, 2004
12     Institute for Sustainable Communities (ISC)\r\...  Jan 13, 2004
13     Food Security Regional Cooperation and Stabili...  Jan 14, 2004
14     Teleplus LLC\r\nJOB TITLE:  General Manager\r\...  Jan 14, 2004
15     NetCall Communications\r\nJOB TITLE:  Network ...  Jan 15, 2004
16     SOC.Stockholm\r\nTITLE:   Utopian World Champi...  Jan 15, 2004
17     United Nations Development Programme, Armenia\...  Jan 15, 2004
18     Counterpart International, Inc.\r\nCounterpart...  Jan 16, 2004
19     Xalt LLC\r\nJOB TITLE:  Graphic Designer\r\nPO...  Jan 16, 2004
20     CUTS Centre for International Trade, Economics...  Jan 19, 2004
21     Yerevan Brandy Company\r\nJOB TITLE:  Lawyer\r...  Jan 19, 2004
22     ACDI/VOCA\r\nJOB TITLE:  Marketing Advisor\r\n...  Jan 19, 2004
23     Armenia TV\r\nJOB TITLE:  Chief/ Supervisor of...  Jan 20, 2004
24     Media Diversity Institute\r\nJOB TITLE:  Journ...  Jan 20, 2004
25     Armenia School Connectivity Program\r\nJOB TIT...  Jan 21, 2004
26     Yerevan State University (YSU) and Civic Educa...  Jan 21, 2004
27     Media Diversity Institute\r\nJOB TITLE:  Repor...  Jan 21, 2004
28     Media Diversity Institute\r\nTITLE:   Reportin...  Jan 21, 2004
29     SEF International\r\nJOB TITLE:  Chief Account...  Jan 23, 2004
...                                                  ...           ...
18971  Career Center NGO\r\n\r\n\r\nTITLE:  Reception...  Dec 22, 2015
18972  Essential Solutions LLC\r\n\r\n\r\nTITLE:  Jav...  Dec 22, 2015
18973  Essential Solutions LLC\r\n\r\n\r\nTITLE:  Sen...  Dec 22, 2015
18974  LTX-Credence Armenia LLC\r\n\r\n\r\nTITLE:  CA...  Dec 23, 2015
18975  LTX-Credence Armenia LLC\r\n\r\n\r\nTITLE:  In...  Dec 23, 2015
18976  SAS Group LLC\r\n\r\n\r\nTITLE:  Senior Financ...  Dec 22, 2015
18977  Strategic Development Agency (SDA) NGO\r\n\r\n...  Dec 22, 2015
18978  Representation of the "French Office for Immig...  Dec 22, 2015
18979  Care Building Services LLC\r\n\r\n\r\nTITLE:  ...  Dec 23, 2015
18980  LTX-Credence Armenia LLC\r\n\r\n\r\nTITLE:  Ha...  Dec 23, 2015
18981  BDO Armenia CJSC\r\n\r\n\r\nTITLE:  Auditor\r\...  Dec 23, 2015
18982  BDO Armenia CJSC\r\n\r\n\r\nTITLE:  Senior Aud...  Dec 23, 2015
18983  Care Building Services LLC\r\n\r\n\r\nTITLE:  ...  Dec 23, 2015
18984  Care Building Services LLC\r\n\r\n\r\nTITLE:  ...  Dec 23, 2015
18985  Strategic Development Agency (SDA) NGO\r\n\r\n...  Dec 22, 2015
18986  Strategic Development Agency (SDA) NGO\r\n\r\n...  Dec 22, 2015
18987  PicsArt LLC\r\n\r\n\r\nTITLE:  Junior Mobile V...  Dec 24, 2015
18988  Berg Development LLC\r\n\r\n\r\nTITLE:  JavaSc...  Dec 24, 2015
18989  "Transport PIU" State Institution of the RA Mi...  Dec 24, 2015
18990  NASDAQ OMX Armenia OJSC\r\n\r\n\r\nTITLE:  Jav...  Dec 24, 2015
18991  NASDAQ OMX Armenia OJSC\r\n\r\n\r\nTITLE:  C/ ...  Dec 24, 2015
18992  Macadamian AR CJSC\r\n\r\n\r\nTITLE:  .NET Dev...  Dec 25, 2015
18993  "Coca-Cola Hellenic Bottling Company Armenia" ...  Dec 25, 2015
18994  "Coca-Cola Hellenic Bottling Company Armenia" ...  Dec 25, 2015
18995  "Transport PIU" State Institution of the RA Mi...  Dec 24, 2015
18996  Technolinguistics NGO\r\n\r\n\r\nTITLE:  Senio...  Dec 28, 2015
18997  "Coca-Cola Hellenic Bottling Company Armenia" ...  Dec 30, 2015
18998  "Coca-Cola Hellenic Bottling Company Armenia" ...  Dec 30, 2015
18999  San Lazzaro   LLC\r\n\r\n\r\nTITLE:  Head of O...  Dec 30, 2015
19000  "Kamurj" UCO CJSC\r\n\r\n\r\nTITLE:  Lawyer in...  Dec 30, 2015

                                                   Title  \
0                                Chief Financial Officer
1      Full-time Community Connections Intern (paid i...
2                                    Country Coordinator
3                                         BCC Specialist
4                                     Software Developer
5                                             Saleswoman
6                    Chief Accountant/ Finance Assistant
7         Non-paid part or full time Programmatic Intern
8                         Assistant to Managing Director
9                  Program Assistant (INL), FSN-8; FP-6*
10                Short-Term Travel Grants (STG) Program
11      Non-paid part or full time Administrative Intern
12                                  Chief of Party (COP)
13     Community Development, Capacity Building and C...
14                                       General Manager
15                                 Network Administrator
16                       Utopian World Championship 2004
17                               Country Economist (NOB)
18                           Driver/ Logistics Assistant
19                                      Graphic Designer
20                              Administrative Assistant
21                                                Lawyer
22                                     Marketing Advisor
23              Chief/ Supervisor of Programs Department
24                                    Journalism Trainer
25                               Deputy Program Director
26     Student Forum: Student Conference and Debate F...
27          Reporting Diversity Workshop for Journalists
28          Reporting Diversity Workshop for Journalists
29                                      Chief Accountant
...                                                  ...
18971             Receptionist/ Administrative Assistant
18972                    Java, Grails/ Groovie Developer
18973                      Senior Java Software Engineer
18974       CAD Librarian (Printed Circuit Board Design)
18975    Intern ( Coop Tech): Precision Analog HW Design
18976                        Senior Financial Specialist
18977                                Business Consultant
18978    National Expert on Socio-Demographic Statistics
18979                                  Project Assistant
18980                                  Hardware Engineer
18981                                            Auditor
18982                                     Senior Auditor
18983                          Construction Site Manager
18984                                Electrical Engineer
18985                                  Project Assistant
18986                        Public Relations Specialist
18987               Junior Mobile Visual UI/ UX Designer
18988                            JavaScript Professional
18989  Leading Specialist/ Accountant of Financial an...
18990                                     Java Developer
18991                                   C/ C++ Developer
18992                                     .NET Developer
18993                             Recruitment Specialist
18994                  Capability Development Specialist
18995                                    Deputy Director
18996                    Senior Creative UX/ UI Designer
18997                       Category Development Manager
18998                      Operational Marketing Manager
18999                    Head of Online Sales Department
19000                         Lawyer in Legal Department

                                                 Company AnnouncementCode  \
0                   AMERIA Investment Consulting Company              NaN
1        International Research & Exchanges Board (IREX)              NaN
2              Caucasus Environmental NGO Network (CENN)              NaN
3                                           Manoff Group              NaN
4                                 Yerevan Brandy Company              NaN
5                                     Boutique "Appollo"              NaN
6      OSI Assistance Foundation - Armenian Branch Of...              NaN
7        International Research & Exchanges Board (IREX)              NaN
8                                 Yerevan Brandy Company              NaN
9      American Embassy Yerevan\r\nANNOUNCEMENT NUMBE...              NaN
10       International Research & Exchanges Board (IREX)              NaN
11       International Research & Exchanges Board (IREX)              NaN
12           Institute for Sustainable Communities (ISC)              NaN
13     Food Security Regional Cooperation and Stabili...              NaN
14                                          Teleplus LLC              NaN
15                                NetCall Communications              NaN
16                                         SOC.Stockholm              NaN
17         United Nations Development Programme, Armenia              NaN
18     Counterpart International, Inc.\r\nCounterpart...              NaN
19                                              Xalt LLC              NaN
20     CUTS Centre for International Trade, Economics...              NaN
21                                Yerevan Brandy Company              NaN
22                                             ACDI/VOCA              NaN
23                                            Armenia TV              NaN
24                             Media Diversity Institute              NaN
25                   Armenia School Connectivity Program              NaN
26     Yerevan State University (YSU) and Civic Educa...              NaN
27                             Media Diversity Institute              NaN
28                             Media Diversity Institute              NaN
29                                     SEF International              NaN
...                                                  ...              ...
18971                                  Career Center NGO              NaN
18972                            Essential Solutions LLC              NaN
18973                            Essential Solutions LLC              NaN
18974                           LTX-Credence Armenia LLC              NaN
18975                           LTX-Credence Armenia LLC              NaN
18976                                      SAS Group LLC              NaN
18977             Strategic Development Agency (SDA) NGO              NaN
18978  Representation of the "French Office for Immig...              NaN
18979                         Care Building Services LLC              NaN
18980                           LTX-Credence Armenia LLC              NaN
18981                                   BDO Armenia CJSC              NaN
18982                                   BDO Armenia CJSC              NaN
18983                         Care Building Services LLC              NaN
18984                         Care Building Services LLC              NaN
18985             Strategic Development Agency (SDA) NGO              NaN
18986             Strategic Development Agency (SDA) NGO              NaN
18987                                        PicsArt LLC              NaN
18988                               Berg Development LLC              NaN
18989  "Transport PIU" State Institution of the RA Mi...              NaN
18990                            NASDAQ OMX Armenia OJSC              NaN
18991                            NASDAQ OMX Armenia OJSC              NaN
18992                                 Macadamian AR CJSC              NaN
18993  "Coca-Cola Hellenic Bottling Company Armenia" ...              NaN
18994  "Coca-Cola Hellenic Bottling Company Armenia" ...              NaN
18995  "Transport PIU" State Institution of the RA Mi...              NaN
18996                              Technolinguistics NGO              NaN
18997  "Coca-Cola Hellenic Bottling Company Armenia" ...              NaN
18998  "Coca-Cola Hellenic Bottling Company Armenia" ...              NaN
18999                                  San Lazzaro   LLC              NaN
19000                                  "Kamurj" UCO CJSC              NaN

                       Term                               Eligibility  \
0                       NaN                                       NaN
1                       NaN                                       NaN
2                       NaN                                       NaN
3                       NaN                                       NaN
4                       NaN                                       NaN
5                       NaN                                       NaN
6                       NaN                                       NaN
7                       NaN                                       NaN
8                       NaN                                       NaN
9                       NaN                                       NaN
10                      NaN                                       NaN
11                      NaN                                       NaN
12                      NaN                                       NaN
13                      NaN                                       NaN
14                      NaN                                       NaN
15                      NaN                                       NaN
16                      NaN                                       NaN
17                      NaN                                       NaN
18                      NaN                                       NaN
19                      NaN                                       NaN
20                      NaN                                       NaN
21                      NaN                                       NaN
22                      NaN                                       NaN
23                      NaN                                       NaN
24                      NaN                                       NaN
25                      NaN                                       NaN
26                      NaN                                       NaN
27                      NaN                                       NaN
28                      NaN                                       NaN
29                      NaN                                       NaN
...                     ...                                       ...
18971  Part-time/ Full-time                                  Everyone
18972                   NaN                                       NaN
18973                   NaN                                       NaN
18974                   NaN                                       NaN
18975                   NaN                                       NaN
18976                   NaN                                       NaN
18977                   NaN                                       NaN
18978                   NaN                                       NaN
18979                   NaN                  All eligible candidates.
18980                   NaN                                       NaN
18981                   NaN                                       NaN
18982                   NaN                                       NaN
18983                   NaN                  All eligible candidates.
18984                   NaN                  All eligible candidates.
18985                   NaN                                       NaN
18986                   NaN                                       NaN
18987                   NaN                                       NaN
18988             Full-time                                       NaN
18989                   NaN  All interested and qualified candidates.
18990             Full-time                                       NaN
18991             Full-time                                       NaN
18992                   NaN                                       NaN
18993             Full-time                All interested candidates.
18994                   NaN                All interested candidates.
18995                   NaN  All interested and qualified candidates.
18996             Full-time                                       NaN
18997             Full-time             All interested professionals.
18998             Full-time             All interested professionals.
18999                   NaN                                       NaN
19000             Full-time                                       NaN

      Audience             StartDate  \
0          NaN                   NaN
1          NaN                   NaN
2          NaN                   NaN
3          NaN                   NaN
4          NaN                   NaN
5          NaN                   NaN
6          NaN                   NaN
7          NaN                   NaN
8          NaN                   NaN
9          NaN                   NaN
10         NaN                   NaN
11         NaN                   NaN
12         NaN                   NaN
13         NaN                   NaN
14         NaN                   NaN
15         NaN                   NaN
16         NaN                   NaN
17         NaN                   NaN
18         NaN                   NaN
19         NaN                   NaN
20         NaN                   NaN
21         NaN                   NaN
22         NaN                   NaN
23         NaN                   NaN
24         NaN                   NaN
25         NaN                   NaN
26         NaN                   NaN
27         NaN                   NaN
28         NaN                   NaN
29         NaN                   NaN
...        ...                   ...
18971      NaN                  ASAP
18972      NaN                   NaN
18973      NaN                  ASAP
18974      NaN                   NaN
18975      NaN                   NaN
18976      NaN                  ASAP
18977      NaN                   NaN
18978      NaN      15 February 2015
18979      NaN           Immediately
18980      NaN                   NaN
18981      NaN                  ASAP
18982      NaN                  ASAP
18983      NaN           Immediately
18984      NaN           Immediately
18985      NaN                   NaN
18986      NaN                   NaN
18987      NaN                  ASAP
18988      NaN           Immediately
18989      NaN  As soon as possible.
18990      NaN                   NaN
18991      NaN                   NaN
18992      NaN                   NaN
18993      NaN                  ASAP
18994      NaN                  ASAP
18995      NaN  As soon as possible.
18996      NaN                   NaN
18997      NaN                  ASAP
18998      NaN                  ASAP
18999      NaN                   NaN
19000      NaN                   NaN

                                                Duration  ...    \
0                                                    NaN  ...
1                                               3 months  ...
2                  Renewable annual contract\r\nPOSITION  ...
3                                                    NaN  ...
4                                                    NaN  ...
5                                                    NaN  ...
6                                                    NaN  ...
7                                               6 months  ...
8                                                    NaN  ...
9                                                    NaN  ...
10                                                   NaN  ...

In [33]:
ja.columns

Index(['jobpost', 'date', 'Title', 'Company', 'AnnouncementCode', 'Term',
       'Eligibility', 'Audience', 'StartDate', 'Duration', 'Location',
       'JobDescription', 'JobRequirment', 'RequiredQual', 'Salary',
       'ApplicationP', 'OpeningDate', 'Deadline', 'Notes', 'AboutC', 'Attach',
       'Year', 'Month', 'IT'],
      dtype='object')

In [32]:
ja.head()

,jobpost,date,Title,Company,AnnouncementCode,Term,Eligibility,Audience,StartDate,Duration,...,Salary,ApplicationP,OpeningDate,Deadline,Notes,AboutC,Attach,Year,Month,IT
0,AMERIA Investment Consulting Company\r\nJOB TI...,"Jan 5, 2004",Chief Financial Officer,AMERIA Investment Consulting Company,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,"To apply for this position, please submit a\r\...",NaN,26 January 2004,NaN,NaN,NaN,2004,1,False
1,International Research & Exchanges Board (IREX...,"Jan 7, 2004",Full-time Community Connections Intern (paid i...,International Research & Exchanges Board (IREX),NaN,NaN,NaN,NaN,NaN,3 months,...,NaN,Please submit a cover letter and resume to:\r\...,NaN,12 January 2004,NaN,The International Research & Exchanges Board (...,NaN,2004,1,False
2,Caucasus Environmental NGO Network (CENN)\r\nJ...,"Jan 7, 2004",Country Coordinator,Caucasus Environmental NGO Network (CENN),NaN,NaN,NaN,NaN,NaN,Renewable annual contract\r\nPOSITION,...,NaN,Please send resume or CV toursula.kazarian@......,NaN,20 January 2004\r\nSTART DATE: February 2004,NaN,The Caucasus Environmental NGO Network is a\r\...,NaN,2004,1,False
3,Manoff Group\r\nJOB TITLE: BCC Specialist\r\n...,"Jan 7, 2004",BCC Specialist,Manoff Group,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,Please send cover letter and resume to Amy\r\n...,NaN,23 January 2004\r\nSTART DATE: Immediate,NaN,NaN,NaN,2004,1,False
4,Yerevan Brandy Company\r\nJOB TITLE: Software...,"Jan 10, 2004",Software Developer,Yerevan Brandy Company,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,Successful candidates should submit\r\n- CV; \...,NaN,"20 January 2004, 18:00",NaN,NaN,NaN,2004,1,True

In [18]:
ja.shape

(19001, 24)

In [19]:
ja.describe

<bound method NDFrame.describe of                                                  jobpost          date  \
0      AMERIA Investment Consulting Company\r\nJOB TI...   Jan 5, 2004
1      International Research & Exchanges Board (IREX...   Jan 7, 2004
2      Caucasus Environmental NGO Network (CENN)\r\nJ...   Jan 7, 2004
3      Manoff Group\r\nJOB TITLE:  BCC Specialist\r\n...   Jan 7, 2004
4      Yerevan Brandy Company\r\nJOB TITLE:  Software...  Jan 10, 2004
5      Boutique "Appollo"\r\nJOB TITLE:  Saleswoman\r...  Jan 10, 2004
6      OSI Assistance Foundation - Armenian Branch Of...  Jan 11, 2004
7      International Research & Exchanges Board (IREX...  Jan 13, 2004
8      Yerevan Brandy Company \r\nJOB TITLE:  Assista...  Jan 13, 2004
9      American Embassy Yerevan\r\nANNOUNCEMENT NUMBE...  Jan 13, 2004
10     International Research & Exchanges Board (IREX...  Jan 13, 2004
11     International Research & Exchanges Board (IREX...  Jan 13, 2004
12     Institute for Sustainable Communities (ISC)\r\...  Jan 13, 2004
13     Food Security Regional Cooperation and Stabili...  Jan 14, 2004
14     Teleplus LLC\r\nJOB TITLE:  General Manager\r\...  Jan 14, 2004
15     NetCall Communications\r\nJOB TITLE:  Network ...  Jan 15, 2004
16     SOC.Stockholm\r\nTITLE:   Utopian World Champi...  Jan 15, 2004
17     United Nations Development Programme, Armenia\...  Jan 15, 2004
18     Counterpart International, Inc.\r\nCounterpart...  Jan 16, 2004
19     Xalt LLC\r\nJOB TITLE:  Graphic Designer\r\nPO...  Jan 16, 2004
20     CUTS Centre for International Trade, Economics...  Jan 19, 2004
21     Yerevan Brandy Company\r\nJOB TITLE:  Lawyer\r...  Jan 19, 2004
22     ACDI/VOCA\r\nJOB TITLE:  Marketing Advisor\r\n...  Jan 19, 2004
23     Armenia TV\r\nJOB TITLE:  Chief/ Supervisor of...  Jan 20, 2004
24     Media Diversity Institute\r\nJOB TITLE:  Journ...  Jan 20, 2004
25     Armenia School Connectivity Program\r\nJOB TIT...  Jan 21, 2004
26     Yerevan State University (YSU) and Civic Educa...  Jan 21, 2004
27     Media Diversity Institute\r\nJOB TITLE:  Repor...  Jan 21, 2004
28     Media Diversity Institute\r\nTITLE:   Reportin...  Jan 21, 2004
29     SEF International\r\nJOB TITLE:  Chief Account...  Jan 23, 2004
...                                                  ...           ...
18971  Career Center NGO\r\n\r\n\r\nTITLE:  Reception...  Dec 22, 2015
18972  Essential Solutions LLC\r\n\r\n\r\nTITLE:  Jav...  Dec 22, 2015
18973  Essential Solutions LLC\r\n\r\n\r\nTITLE:  Sen...  Dec 22, 2015
18974  LTX-Credence Armenia LLC\r\n\r\n\r\nTITLE:  CA...  Dec 23, 2015
18975  LTX-Credence Armenia LLC\r\n\r\n\r\nTITLE:  In...  Dec 23, 2015
18976  SAS Group LLC\r\n\r\n\r\nTITLE:  Senior Financ...  Dec 22, 2015
18977  Strategic Development Agency (SDA) NGO\r\n\r\n...  Dec 22, 2015
18978  Representation of the "French Office for Immig...  Dec 22, 2015
18979  Care Building Services LLC\r\n\r\n\r\nTITLE:  ...  Dec 23, 2015
18980  LTX-Credence Armenia LLC\r\n\r\n\r\nTITLE:  Ha...  Dec 23, 2015
18981  BDO Armenia CJSC\r\n\r\n\r\nTITLE:  Auditor\r\...  Dec 23, 2015
18982  BDO Armenia CJSC\r\n\r\n\r\nTITLE:  Senior Aud...  Dec 23, 2015
18983  Care Building Services LLC\r\n\r\n\r\nTITLE:  ...  Dec 23, 2015
18984  Care Building Services LLC\r\n\r\n\r\nTITLE:  ...  Dec 23, 2015
18985  Strategic Development Agency (SDA) NGO\r\n\r\n...  Dec 22, 2015
18986  Strategic Development Agency (SDA) NGO\r\n\r\n...  Dec 22, 2015
18987  PicsArt LLC\r\n\r\n\r\nTITLE:  Junior Mobile V...  Dec 24, 2015
18988  Berg Development LLC\r\n\r\n\r\nTITLE:  JavaSc...  Dec 24, 2015
18989  "Transport PIU" State Institution of the RA Mi...  Dec 24, 2015
18990  NASDAQ OMX Armenia OJSC\r\n\r\n\r\nTITLE:  Jav...  Dec 24, 2015
18991  NASDAQ OMX Armenia OJSC\r\n\r\n\r\nTITLE:  C/ ...  Dec 24, 2015
18992  Macadamian AR CJSC\r\n\r\n\r\nTITLE:  .NET Dev...  Dec 25, 2015
18993  "Coca-Cola Hellenic Bottling Company Armenia" ...  Dec 25, 2015
18994  "Coca-Cola Hellenic Bottling Company Armenia" ...  Dec 25, 2015
18995  "Transport PIU" State Institution of the RA Mi...  Dec 24, 2015
18996  Technolinguistics NGO\r\n\r\n\r\nTITLE:  Senio...  Dec 28, 2015
18997  "Coca-Cola Hellenic Bottling Company Armenia" ...  Dec 30, 2015
18998  "Coca-Cola Hellenic Bottling Company Armenia" ...  Dec 30, 2015
18999  San Lazzaro   LLC\r\n\r\n\r\nTITLE:  Head of O...  Dec 30, 2015
19000  "Kamurj" UCO CJSC\r\n\r\n\r\nTITLE:  Lawyer in...  Dec 30, 2015

                                                   Title  \
0                                Chief Financial Officer
1      Full-time Community Connections Intern (paid i...
2                                    Country Coordinator
3                                         BCC Specialist
4                                     Software Developer
5                                             Saleswoman
6                    Chief Accountant/ Finance Assistant
7         Non-paid part or full time Programmatic Intern
8                         Assistant to Managing Director
9                  Program Assistant (INL), FSN-8; FP-6*
10                Short-Term Travel Grants (STG) Program
11      Non-paid part or full time Administrative Intern
12                                  Chief of Party (COP)
13     Community Development, Capacity Building and C...
14                                       General Manager
15                                 Network Administrator
16                       Utopian World Championship 2004
17                               Country Economist (NOB)
18                           Driver/ Logistics Assistant
19                                      Graphic Designer
20                              Administrative Assistant
21                                                Lawyer
22                                     Marketing Advisor
23              Chief/ Supervisor of Programs Department
24                                    Journalism Trainer
25                               Deputy Program Director
26     Student Forum: Student Conference and Debate F...
27          Reporting Diversity Workshop for Journalists
28          Reporting Diversity Workshop for Journalists
29                                      Chief Accountant
...                                                  ...
18971             Receptionist/ Administrative Assistant
18972                    Java, Grails/ Groovie Developer
18973                      Senior Java Software Engineer
18974       CAD Librarian (Printed Circuit Board Design)
18975    Intern ( Coop Tech): Precision Analog HW Design
18976                        Senior Financial Specialist
18977                                Business Consultant
18978    National Expert on Socio-Demographic Statistics
18979                                  Project Assistant
18980                                  Hardware Engineer
18981                                            Auditor
18982                                     Senior Auditor
18983                          Construction Site Manager
18984                                Electrical Engineer
18985                                  Project Assistant
18986                        Public Relations Specialist
18987               Junior Mobile Visual UI/ UX Designer
18988                            JavaScript Professional
18989  Leading Specialist/ Accountant of Financial an...
18990                                     Java Developer
18991                                   C/ C++ Developer
18992                                     .NET Developer
18993                             Recruitment Specialist
18994                  Capability Development Specialist
18995                                    Deputy Director
18996                    Senior Creative UX/ UI Designer
18997                       Category Development Manager
18998                      Operational Marketing Manager
18999                    Head of Online Sales Department
19000                         Lawyer in Legal Department

                                                 Company AnnouncementCode  \
0                   AMERIA Investment Consulting Company              NaN
1        International Research & Exchanges Board (IREX)              NaN
2              Caucasus Environmental NGO Network (CENN)              NaN
3                                           Manoff Group              NaN
4                                 Yerevan Brandy Company              NaN
5                                     Boutique "Appollo"              NaN
6      OSI Assistance Foundation - Armenian Branch Of...              NaN
7        International Research & Exchanges Board (IREX)              NaN
8                                 Yerevan Brandy Company              NaN
9      American Embassy Yerevan\r\nANNOUNCEMENT NUMBE...              NaN
10       International Research & Exchanges Board (IREX)              NaN
11       International Research & Exchanges Board (IREX)              NaN
12           Institute for Sustainable Communities (ISC)              NaN
13     Food Security Regional Cooperation and Stabili...              NaN
14                                          Teleplus LLC              NaN
15                                NetCall Communications              NaN
16                                         SOC.Stockholm              NaN
17         United Nations Development Programme, Armenia              NaN
18     Counterpart International, Inc.\r\nCounterpart...              NaN
19                                              Xalt LLC              NaN
20     CUTS Centre for International Trade, Economics...              NaN
21                                Yerevan Brandy Company              NaN
22                                             ACDI/VOCA              NaN
23                                            Armenia TV              NaN
24                             Media Diversity Institute              NaN
25                   Armenia School Connectivity Program              NaN
26     Yerevan State University (YSU) and Civic Educa...              NaN
27                             Media Diversity Institute              NaN
28                             Media Diversity Institute              NaN
29                                     SEF International              NaN
...                                                  ...              ...
18971                                  Career Center NGO              NaN
18972                            Essential Solutions LLC              NaN
18973                            Essential Solutions LLC              NaN
18974                           LTX-Credence Armenia LLC              NaN
18975                           LTX-Credence Armenia LLC              NaN
18976                                      SAS Group LLC              NaN
18977             Strategic Development Agency (SDA) NGO              NaN
18978  Representation of the "French Office for Immig...              NaN
18979                         Care Building Services LLC              NaN
18980                           LTX-Credence Armenia LLC              NaN
18981                                   BDO Armenia CJSC              NaN
18982                                   BDO Armenia CJSC              NaN
18983                         Care Building Services LLC              NaN
18984                         Care Building Services LLC              NaN
18985             Strategic Development Agency (SDA) NGO              NaN
18986             Strategic Development Agency (SDA) NGO              NaN
18987                                        PicsArt LLC              NaN
18988                               Berg Development LLC              NaN
18989  "Transport PIU" State Institution of the RA Mi...              NaN
18990                            NASDAQ OMX Armenia OJSC              NaN
18991                            NASDAQ OMX Armenia OJSC              NaN
18992                                 Macadamian AR CJSC              NaN
18993  "Coca-Cola Hellenic Bottling Company Armenia" ...              NaN
18994  "Coca-Cola Hellenic Bottling Company Armenia" ...              NaN
18995  "Transport PIU" State Institution of the RA Mi...              NaN
18996                              Technolinguistics NGO              NaN
18997  "Coca-Cola Hellenic Bottling Company Armenia" ...              NaN
18998  "Coca-Cola Hellenic Bottling Company Armenia" ...              NaN
18999                                  San Lazzaro   LLC              NaN
19000                                  "Kamurj" UCO CJSC              NaN

                       Term                               Eligibility  \
0                       NaN                                       NaN
1                       NaN                                       NaN
2                       NaN                                       NaN
3                       NaN                                       NaN
4                       NaN                                       NaN
5                       NaN                                       NaN
6                       NaN                                       NaN
7                       NaN                                       NaN
8                       NaN                                       NaN
9                       NaN                                       NaN
10                      NaN                                       NaN
11                      NaN                                       NaN
12                      NaN                                       NaN
13                      NaN                                       NaN
14                      NaN                                       NaN
15                      NaN                                       NaN
16                      NaN                                       NaN
17                      NaN                                       NaN
18                      NaN                                       NaN
19                      NaN                                       NaN
20                      NaN                                       NaN
21                      NaN                                       NaN
22                      NaN                                       NaN
23                      NaN                                       NaN
24                      NaN                                       NaN
25                      NaN                                       NaN
26                      NaN                                       NaN
27                      NaN                                       NaN
28                      NaN                                       NaN
29                      NaN                                       NaN
...                     ...                                       ...
18971  Part-time/ Full-time                                  Everyone
18972                   NaN                                       NaN
18973                   NaN                                       NaN
18974                   NaN                                       NaN
18975                   NaN                                       NaN
18976                   NaN                                       NaN
18977                   NaN                                       NaN
18978                   NaN                                       NaN
18979                   NaN                  All eligible candidates.
18980                   NaN                                       NaN
18981                   NaN                                       NaN
18982                   NaN                                       NaN
18983                   NaN                  All eligible candidates.
18984                   NaN                  All eligible candidates.
18985                   NaN                                       NaN
18986                   NaN                                       NaN
18987                   NaN                                       NaN
18988             Full-time                                       NaN
18989                   NaN  All interested and qualified candidates.
18990             Full-time                                       NaN
18991             Full-time                                       NaN
18992                   NaN                                       NaN
18993             Full-time                All interested candidates.
18994                   NaN                All interested candidates.
18995                   NaN  All interested and qualified candidates.
18996             Full-time                                       NaN
18997             Full-time             All interested professionals.
18998             Full-time             All interested professionals.
18999                   NaN                                       NaN
19000             Full-time                                       NaN

      Audience             StartDate  \
0          NaN                   NaN
1          NaN                   NaN
2          NaN                   NaN
3          NaN                   NaN
4          NaN                   NaN
5          NaN                   NaN
6          NaN                   NaN
7          NaN                   NaN
8          NaN                   NaN
9          NaN                   NaN
10         NaN                   NaN
11         NaN                   NaN
12         NaN                   NaN
13         NaN                   NaN
14         NaN                   NaN
15         NaN                   NaN
16         NaN                   NaN
17         NaN                   NaN
18         NaN                   NaN
19         NaN                   NaN
20         NaN                   NaN
21         NaN                   NaN
22         NaN                   NaN
23         NaN                   NaN
24         NaN                   NaN
25         NaN                   NaN
26         NaN                   NaN
27         NaN                   NaN
28         NaN                   NaN
29         NaN                   NaN
...        ...                   ...
18971      NaN                  ASAP
18972      NaN                   NaN
18973      NaN                  ASAP
18974      NaN                   NaN
18975      NaN                   NaN
18976      NaN                  ASAP
18977      NaN                   NaN
18978      NaN      15 February 2015
18979      NaN           Immediately
18980      NaN                   NaN
18981      NaN                  ASAP
18982      NaN                  ASAP
18983      NaN           Immediately
18984      NaN           Immediately
18985      NaN                   NaN
18986      NaN                   NaN
18987      NaN                  ASAP
18988      NaN           Immediately
18989      NaN  As soon as possible.
18990      NaN                   NaN
18991      NaN                   NaN
18992      NaN                   NaN
18993      NaN                  ASAP
18994      NaN                  ASAP
18995      NaN  As soon as possible.
18996      NaN                   NaN
18997      NaN                  ASAP
18998      NaN                  ASAP
18999      NaN                   NaN
19000      NaN                   NaN

                                                Duration  ...    \
0                                                    NaN  ...
1                                               3 months  ...
2                  Renewable annual contract\r\nPOSITION  ...
3                                                    NaN  ...
4                                                    NaN  ...
5                                                    NaN  ...
6                                                    NaN  ...
7                                               6 months  ...
8                                                    NaN  ...
9                                                    NaN  ...
10                                                   NaN  ...

In [39]:
ja['date']

0         Jan 5, 2004
1         Jan 7, 2004
2         Jan 7, 2004
3         Jan 7, 2004
4        Jan 10, 2004
5        Jan 10, 2004
6        Jan 11, 2004
7        Jan 13, 2004
8        Jan 13, 2004
9        Jan 13, 2004
10       Jan 13, 2004
11       Jan 13, 2004
12       Jan 13, 2004
13       Jan 14, 2004
14       Jan 14, 2004
15       Jan 15, 2004
16       Jan 15, 2004
17       Jan 15, 2004
18       Jan 16, 2004
19       Jan 16, 2004
20       Jan 19, 2004
21       Jan 19, 2004
22       Jan 19, 2004
23       Jan 20, 2004
24       Jan 20, 2004
25       Jan 21, 2004
26       Jan 21, 2004
27       Jan 21, 2004
28       Jan 21, 2004
29       Jan 23, 2004
             ...
18971    Dec 22, 2015
18972    Dec 22, 2015
18973    Dec 22, 2015
18974    Dec 23, 2015
18975    Dec 23, 2015
18976    Dec 22, 2015
18977    Dec 22, 2015
18978    Dec 22, 2015
18979    Dec 23, 2015
18980    Dec 23, 2015
18981    Dec 23, 2015
18982    Dec 23, 2015
18983    Dec 23, 2015
18984    Dec 23, 2015
18985    Dec 22, 2015
18986    Dec 22, 2015
18987    Dec 24, 2015
18988    Dec 24, 2015
18989    Dec 24, 2015
18990    Dec 24, 2015
18991    Dec 24, 2015
18992    Dec 25, 2015
18993    Dec 25, 2015
18994    Dec 25, 2015
18995    Dec 24, 2015
18996    Dec 28, 2015
18997    Dec 30, 2015
18998    Dec 30, 2015
18999    Dec 30, 2015
19000    Dec 30, 2015
Name: date, Length: 19001, dtype: object

In [20]:
g = ja.groupby(['date'])

In [41]:
g.count()

,jobpost,Title,Company,AnnouncementCode,Term,Eligibility,Audience,StartDate,Duration,Location,...,Salary,ApplicationP,OpeningDate,Deadline,Notes,AboutC,Attach,Year,Month,IT
date,,,,,,,,,,,,,,,,,,,,,
Apr 1,11,11,11,0,2,1,0,5,9,11,...,5,11,11,11,0,9,4,11,11,11
"Apr 1, 2004",7,7,7,0,0,0,0,0,0,7,...,0,7,0,7,0,5,0,7,7,7
"Apr 1, 2008",7,7,7,0,2,5,0,5,7,7,...,6,7,7,7,0,6,0,7,7,7
"Apr 1, 2009",2,2,2,0,1,2,0,2,1,2,...,1,2,2,2,1,1,0,2,2,2
"Apr 1, 2010",6,6,6,0,5,4,0,2,4,6,...,4,6,6,6,0,6,0,6,6,6
"Apr 1, 2011",5,5,5,0,2,1,0,3,4,5,...,2,5,5,5,1,3,1,5,5,5
"Apr 1, 2012",4,4,4,0,0,0,0,1,1,4,...,1,4,4,4,1,0,0,4,4,4
"Apr 1, 2014",9,9,9,0,2,3,1,5,6,9,...,1,9,9,9,0,9,2,9,9,9
Apr 10,10,10,10,0,8,2,0,8,6,10,...,4,10,10,10,1,5,3,10,10,10
"Apr 10, 2004",2,2,2,0,0,0,0,0,0,2,...,0,2,0,2,0,0,0,2,2,2
"Apr 10, 2006",9,9,9,1,3,1,0,2,4,9,...,4,9,9,9,1,4,1,9,9,9
"Apr 10, 2007",4,4,4,1,1,1,0,2,1,4,...,1,4,4,4,1,4,0,4,4,4
"Apr 10, 2008",6,6,6,1,4,1,0,3,4,6,...,3,6,6,6,1,5,0,6,6,6
"Apr 10, 2009",3,3,3,0,2,1,0,1,2,3,...,2,3,3,3,1,3,0,3,3,3
"Apr 10, 2012",9,9,9,1,5,4,0,7,6,9,...,6,9,9,9,0,5,0,9,9,9
"Apr 10, 2013",13,13,13,1,3,2,2,6,5,13,...,9,13,12,13,2,10,1,13,13,13
"Apr 10, 2014",5,5,5,0,5,2,0,3,5,5,...,2,5,5,5,2,5,0,5,5,5
Apr 11,6,6,6,0,4,4,0,4,5,6,...,4,6,6,6,0,3,0,6,6,6
"Apr 11, 2005",5,5,5,1,2,3,1,2,2,5,...,3,5,5,5,0,3,1,5,5,5
"Apr 11, 2006",4,4,4,0,0,1,0,0,0,4,...,1,4,4,4,0,2,0,4,4,4
"Apr 11, 2007",3,3,3,0,2,1,0,3,2,3,...,3,3,3,3,1,3,0,3,3,3
"Apr 11, 2008",4,4,4,0,2,0,0,2,3,4,...,0,4,4,4,0,1,0,4,4,4
"Apr 11, 2010",4,4,4,0,0,1,0,1,3,4,...,1,4,4,4,0,1,1,4,4,4
"Apr 11, 2011",10,10,10,0,5,1,0,9,8,10,...,8,10,10,10,6,8,5,10,10,10
"Apr 11, 2012",9,9,9,0,3,4,0,2,6,9,...,8,9,9,9,0,5,1,9,9,9
"Apr 11, 2013",9,9,9,2,2,0,1,4,7,9,...,4,9,9,9,1,7,0,9,9,9
"Apr 11, 2014",13,13,13,0,6,3,0,6,7,13,...,8,13,13,13,2,11,3,13,13,13
"Apr 12, 2004",3,3,3,0,0,0,0,0,0,3,...,0,3,0,3,0,0,0,3,3,3
"Apr 12, 2005",2,2,2,0,2,0,0,2,2,2,...,2,2,2,2,0,0,0,2,2,2
"Apr 12, 2006",2,2,2,0,1,0,0,0,0,2,...,0,2,2,2,1,0,0,2,2,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
"Sep 7, 2004",8,8,8,0,3,1,0,2,2,8,...,2,8,1,8,0,2,0,8,8,8
"Sep 7, 2005",3,3,3,0,0,1,0,3,3,3,...,3,3,3,3,1,2,0,3,3,3
"Sep 7, 2006",3,3,3,0,2,0,1,3,3,3,...,1,3,3,3,0,2,0,3,3,3
"Sep 7, 2007",5,5,5,0,2,1,0,2,3,5,...,3,5,5,5,1,4,0,5,5,5
"Sep 7, 2008",1,1,1,0,0,0,1,1,1,1,...,1,1,1,1,1,1,0,1,1,1
"Sep 7, 2009",1,1,1,0,0,1,0,0,0,1,...,0,1,0,1,1,1,1,1,1,1
"Sep 7, 2010",5,5,5,0,3,2,0,4,4,5,...,1,5,5,5,0,4,2,5,5,5
"Sep 7, 2011",6,6,6,1,1,0,2,2,2,6,...,3,6,6,6,1,3,2,6,6,6
"Sep 7, 2012",8,8,8,0,3,2,1,3,2,8,...,4,8,8,8,0,5,0,8,8,8
"Sep 7, 2014",5,5,5,0,3,0,0,5,4,5,...,1,5,5,5,0,4,1,5,5,5
"Sep 7, 2015",3,3,3,0,0,0,0,1,2,3,...,1,3,3,3,0,1,0,3,3,3
"Sep 8, 2004",5,5,5,0,0,0,1,0,0,5,...,1,4,0,4,0,1,0,5,5,5
"Sep 8, 2005",4,4,4,0,4,0,0,2,2,4,...,0,4,4,4,0,2,0,4,4,4
"Sep 8, 2006",3,3,3,1,0,2,0,1,0,3,...,1,3,3,3,3,1,0,3,3,3
"Sep 8, 2008",6,6,6,0,3,3,1,5,4,6,...,2,6,6,6,0,5,0,6,6,6
"Sep 8, 2009",7,7,7,0,3,4,0,4,3,7,...,4,7,7,7,3,6,0,7,7,7
"Sep 8, 2010",8,8,8,0,4,3,0,4,7,8,...,3,8,8,8,2,7,0,8,8,8
"Sep 8, 2011",5,5,5,0,0,1,1,2,3,5,...,3,5,5,5,0,4,2,5,5,5
"Sep 8, 2013",1,1,1,0,1,0,0,0,0,1,...,0,1,1,1,0,0,0,1,1,1
"Sep 8, 2015",3,3,3,0,0,0,0,1,2,3,...,2,3,3,3,0,2,0,3,3,3
"Sep 9, 2004",1,1,1,1,0,1,1,0,0,1,...,0,1,1,1,0,1,0,1,1,1
"Sep 9, 2005",4,4,4,1,4,0,0,1,2,4,...,3,4,4,4,0,3,0,4,4,4
"Sep 9, 2008",4,4,4,0,3,0,0,1,2,4,...,3,4,4,4,0,3,0,4,4,4
"Sep 9, 2009",2,2,2,0,1,1,0,1,1,2,...,0,2,2,2,0,1,0,2,2,2
"Sep 9, 2010",2,2,2,1,2,0,0,2,2,2,...,1,2,2,2,0,1,0,2,2,2
"Sep 9, 2011",7,7,7,0,1,0,0,5,3,7,...,3,7,7,7,3,2,1,7,7,7
"Sep 9, 2012",3,3,3,0,1,2,0,0,0,3,...,0,3,3,3,0,1,0,3,3,3
"Sep 9, 2013",10,10,10,1,5,2,1,5,6,10,...,6,10,10,10,2,10,0,10,10,10
"Sep 9, 2014",8,8,8,0,3,1,0,5,3,8,...,4,8,8,8,0,5,4,8,8,8
"Sep 9, 2015",8,8,8,0,1,6,1,1,3,8,...,2,8,8,8,6,2,0,8,8,8

In [42]:
g.sum()

               Year  Month   IT
date
Apr 1         22165     44  1.0
Apr 1, 2004   14028     28  1.0
Apr 1, 2008   14056     28  2.0
Apr 1, 2009    4018      8  1.0
Apr 1, 2010   12060     24  0.0
Apr 1, 2011   10055     20  0.0
Apr 1, 2012    8048     16  0.0
Apr 1, 2014   18126     36  1.0
Apr 10        20150     40  3.0
Apr 10, 2004   4008      8  0.0
Apr 10, 2006  18054     36  2.0
Apr 10, 2007   8028     16  0.0
Apr 10, 2008  12048     24  2.0
Apr 10, 2009   6027     12  0.0
Apr 10, 2012  18108     36  5.0
Apr 10, 2013  26169     52  5.0
Apr 10, 2014  10070     20  0.0
Apr 11        12090     24  2.0
Apr 11, 2005  10025     20  1.0
Apr 11, 2006   8024     16  1.0
Apr 11, 2007   6021     12  1.0
Apr 11, 2008   8032     16  1.0
Apr 11, 2010   8040     16  0.0
Apr 11, 2011  20110     40  2.0
Apr 11, 2012  18108     36  4.0
Apr 11, 2013  18117     36  2.0
Apr 11, 2014  26182     52  4.0
Apr 12, 2004   6012     12  0.0
Apr 12, 2005   4010      8  0.0
Apr 12, 2006   4012      8  0.0
...             ...    ...  ...
Sep 7, 2004   16032     72  3.0
Sep 7, 2005    6015     27  0.0
Sep 7, 2006    6018     27  2.0
Sep 7, 2007   10035     45  1.0
Sep 7, 2008    2008      9  1.0
Sep 7, 2009    2009      9  0.0
Sep 7, 2010   10050     45  0.0
Sep 7, 2011   12066     54  1.0
Sep 7, 2012   16096     72  0.0
Sep 7, 2014   10070     45  1.0
Sep 7, 2015    6045     27  1.0
Sep 8, 2004   10020     45  0.0
Sep 8, 2005    8020     36  2.0
Sep 8, 2006    6018     27  0.0
Sep 8, 2008   12048     54  2.0
Sep 8, 2009   14063     63  1.0
Sep 8, 2010   16080     72  0.0
Sep 8, 2011   10055     45  1.0
Sep 8, 2013    2013      9  0.0
Sep 8, 2015    6045     27  0.0
Sep 9, 2004    2004      9  0.0
Sep 9, 2005    8020     36  0.0
Sep 9, 2008    8032     36  2.0
Sep 9, 2009    4018     18  0.0
Sep 9, 2010    4020     18  1.0
Sep 9, 2011   14077     63  1.0
Sep 9, 2012    6036     27  0.0
Sep 9, 2013   20130     90  2.0
Sep 9, 2014   16112     72  2.0
Sep 9, 2015   16120     72  0.0

[4391 rows x 3 columns]

In [44]:
pd.isnull(ja)

,jobpost,date,Title,Company,AnnouncementCode,Term,Eligibility,Audience,StartDate,Duration,...,Salary,ApplicationP,OpeningDate,Deadline,Notes,AboutC,Attach,Year,Month,IT
0,False,False,False,False,True,True,True,True,True,True,...,True,False,True,False,True,True,True,False,False,False
1,False,False,False,False,True,True,True,True,True,False,...,True,False,True,False,True,False,True,False,False,False
2,False,False,False,False,True,True,True,True,True,False,...,True,False,True,False,True,False,True,False,False,False
3,False,False,False,False,True,True,True,True,True,True,...,True,False,True,False,True,True,True,False,False,False
4,False,False,False,False,True,True,True,True,True,True,...,True,False,True,False,True,True,True,False,False,False
5,False,False,False,False,True,True,True,True,True,True,...,True,False,True,False,True,True,True,False,False,False
6,False,False,False,False,True,True,True,True,True,True,...,True,False,True,False,True,True,True,False,False,False
7,False,False,False,False,True,True,True,True,True,False,...,True,False,True,False,True,False,True,False,False,False
8,False,False,False,False,True,True,True,True,True,True,...,True,False,True,False,True,True,True,False,False,False
9,False,False,False,False,True,True,True,True,True,True,...,True,False,True,False,True,True,True,False,False,False
10,False,False,False,False,True,True,True,True,True,True,...,True,False,True,False,True,True,True,False,False,False
11,False,False,False,False,True,True,True,True,True,False,...,True,False,True,False,True,False,True,False,False,False
12,False,False,False,False,True,True,True,True,True,False,...,True,False,True,False,True,False,True,False,False,False
13,False,False,False,False,True,True,True,True,True,True,...,True,False,True,False,True,True,True,False,False,False
14,False,False,False,False,True,True,True,True,True,True,...,True,False,True,False,True,True,True,False,False,False
15,False,False,False,False,True,True,True,True,True,True,...,True,False,True,False,True,True,True,False,False,False
16,False,False,False,False,True,True,True,True,True,True,...,True,False,True,False,True,True,True,False,False,False
17,False,False,False,False,True,True,True,True,True,False,...,True,False,True,False,True,True,True,False,False,False
18,False,False,False,False,True,True,True,True,True,True,...,True,False,True,False,True,True,True,False,False,False
19,False,False,False,False,True,True,True,True,True,True,...,True,False,True,False,True,True,True,False,False,False
20,False,False,False,False,True,True,True,True,True,True,...,True,False,True,False,True,True,True,False,False,False
21,False,False,False,False,True,True,True,True,True,True,...,True,False,True,False,True,True,True,False,False,False
22,False,False,False,False,True,True,True,True,True,False,...,True,False,True,True,True,False,True,False,False,False
23,False,False,False,False,True,True,True,True,True,False,...,True,False,True,False,True,True,True,False,False,False
24,False,False,False,False,True,True,True,True,True,True,...,True,False,True,False,True,False,True,False,False,False
25,False,False,False,False,True,True,True,True,True,True,...,True,False,True,False,True,True,True,False,False,False
26,False,False,False,False,True,True,True,True,True,False,...,True,False,True,False,True,True,True,False,False,False
27,False,False,False,False,True,True,True,True,True,True,...,True,False,True,False,True,False,True,False,False,False
28,False,False,False,False,True,True,True,True,True,False,...,True,False,True,False,True,False,True,False,False,False
29,False,False,False,False,True,True,True,True,True,True,...,True,False,True,False,True,True,True,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18971,False,False,False,False,True,False,False,True,False,True,...,True,False,False,False,False,True,True,False,False,False
18972,False,False,False,False,True,True,True,True,True,True,...,True,False,False,False,True,False,True,False,False,False
18973,False,False,False,False,True,True,True,True,False,False,...,False,False,False,False,True,False,True,False,False,False
18974,False,False,False,False,True,True,True,True,True,True,...,True,False,False,False,True,False,True,False,False,False
18975,False,False,False,False,True,True,True,True,True,True,...,True,False,False,False,True,False,True,False,False,False
18976,False,False,False,False,True,True,True,True,False,False,...,False,False,False,False,True,True,True,False,False,False
18977,False,False,False,False,True,True,True,True,True,False,...,True,False,False,False,True,False,True,False,False,False
18978,False,False,False,False,True,True,True,True,False,False,...,True,False,False,False,True,False,False,False,False,False
18979,False,False,False,False,True,True,False,True,False,False,...,False,False,False,False,True,False,True,False,False,False
18980,False,False,False,False,True,True,True,True,True,True,...,True,False,False,False,True,False,True,False,False,False
18981,False,False,False,False,True,True,True,True,False,True,...,False,False,False,False,True,True,False,False,False,False
18982,False,False,False,False,True,True,True,True,False,True,...,False,False,False,False,True,True,False,False,False,False
18983,False,False,False,False,True,True,False,True,False,False,...,False,False,False,False,True,False,True,False,False,False
18984,False,False,False,False,True,True,False,True,False,False,...,False,False,False,False,True,False,True,False,False,False
18985,False,False,False,False,True,True,True,True,True,False,...,True,False,False,False,True,False,True,False,False,False
18986,False,False,False,False,True,True,True,True,True,False,...,True,False,False,False,True,False,True,False,False,False
18987,False,False,False,False,True,True,True,True,False,False,...,True,False,False,False,True,False,True,False,False,False
18988,False,False,False,False,True,False,True,True,False,True,...,False,False,False,False,False,False,True,False,False,False
18989,False,False,False,False,True,True,False,True,False,False,...,False,False,False,False,True,False,True,False,False,False
18990,False,False,False,False,True,False,True,True,True,True,...,False,False,False,False,True,False,True,False,False,False
18991,False,False,False,False,True,False,True,True,True,True,...,False,False,False,False,True,False,True,False,False,False
18992,False,False,False,False,True,True,True,True,True,True,...,True,False,False,False,True,False,True,False,False,False
18993,False,False,False,False,True,False,False,True,False,False,...,True,False,False,False,True,True,True,False,False,False
18994,False,False,False,False,True,True,False,True,False,False,...,True,False,False,False,True,True,True,False,False,False
18995,False,False,False,False,True,True,False,True,False,False,...,False,False,False,False,True,False,True,False,False,False
18996,False,False,False,False,True,False,True,True,True,False,...,False,False,False,False,True,False,True,False,False,False
18997,False,False,False,False,True,False,False,True,False,False,...,True,False,False,False,True,True,True,False,False,False
18998,False,False,False,False,True,False,False,True,False,False,...,True,False,False,False,True,True,True,False,False,False
18999,False,False,False,False,True,True,True,True,True,False,...,False,False,False,False,True,False,True,False,False,False
19000,False,False,False,False,True,False,True,True,True,False,...,True,False,False,False,True,False,True,False,False,False

In [45]:
ja.apply(lambda x: sum(x.isnull()),axis=0)

jobpost                 0
date                    0
Title                  28
Company                 7
AnnouncementCode    17793
Term                11325
Eligibility         14071
Audience            18361
StartDate            9326
Duration             8203
Location               32
JobDescription       3891
JobRequirment        2522
RequiredQual          484
Salary               9378
ApplicationP           60
OpeningDate           706
Deadline               65
Notes               16790
AboutC               6531
Attach              17442
Year                    0
Month                   0
IT                      0
dtype: int64